#!/usr/bin/env python

"""
//! \brief A script to analyze footwarming temperature data(.csv) file
           generated by Logger Pro software. Assumed that there are 3 columns
           Time, Right_Temp and Left_Temp in the file.
//! \version v1
"""

import sys
import csv
import numpy as np


def usage():
    print("python analyze_temp_csv.py <filename>")


def analyzeData(data, length, time):
    for i in xrange(1, 50):
        if data[i] > data[i - 1]:
            print("Ambient time(min)     : " + str(int(time[i - 1])))
            break

    for i in xrange(10, length):
        if data[i] == data[i - 1]:
            print("Max temperature(F)    : " + str(max(data)))
            print("Settle time(min)      : " + str(int(time[i])))
            break

    for i in xrange(350, length):
        if data[i] != data[i - 1]:
            print("Timeout(min)          : " + str(int(time[i])))
            break


def Main():
    if len(sys.argv) == 2:
        with open(sys.argv[1], 'r') as f:
            data = list(csv.reader(f, delimiter=","))

        data = np.array(data[1:], dtype=np.float)
        time, right, left = data[:, 0], data[:, 1], data[:, 2]
        length = len(time)
        if length < 400:
            print("Given file doesn't have sufficient dataset, exiting!")
            sys.exit(0)

        print("---------------------Right--------------------------------")
        analyzeData(right, length, time)

        print("----------------------Left--------------------------------")
        analyzeData(left, length, time)
        print("-----------------------------------------------------")
    else:
        usage()
        sys.exit(0)


if __name__ == '__main__':
    Main()
